---
# Dependency management (download roles/collections)
dependency:
  name: galaxy

ansible:
  executor:
    backend: ansible-playbook
    # args:
      # ansible_playbook:
        # - --inventory=/workspaces/ansible_m1/nginx/molecule/default/inventory/ansible_inventory.yml
      